import json

template = {
    "type": "CODE_SMELL",
    "status": "ready",
    "tags": [],
    "defaultSeverity": "Minor",
    "scope": "All",
    "sqKey": "",
    "title": ""
}

if __name__ == '__main__':
    with open('credo.json') as f:
        data = json.load(f)
    for item in data['ruleKeys']:
        body = template.copy()
        sub = item.split(".")
        body['tags'] = [sub[2].lower()]
        body['sqKey'] = item
        body['title'] = sub[3]
        with open('%s.json' % item, 'w+') as out:
            json.dump(body, out)
            out.close()
        with open('%s.html' % item, 'w+') as out:
            out.write('<h1>%s</h1>' % sub[3])
            out.write('<p>Generated by program</p>')
            out.close()
